services:
  # OpenSearch Node
  opensearch-node:
    image: opensearchproject/opensearch:2.11.1
    platform: linux/amd64
    container_name: opensearch-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./config/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  # OpenSearch Dashboards
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    platform: linux/amd64
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    volumes:
      - ./config/opensearch/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node

  # Data Prepper
  data-prepper:
    image: opensearchproject/data-prepper:2.6.1
    platform: linux/amd64
    container_name: data-prepper
    environment:
      - "DATA_PREPPER_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "21890:21890" # OTLP gRPC (Traces)
      - "21891:21891" # OTLP gRPC (Metrics)
      - "21892:21892" # OTLP gRPC (Logs)
      - "4900:4900" # Data Prepper Server
    volumes:
      - ./config/data-prepper/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./config/data-prepper/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node

  # Demo Application with OpenTelemetry
  demo-app:
    platform: linux/amd64
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: demo-app
    environment:
      - PYTHONUNBUFFERED=1
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=data-prepper:21890
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=data-prepper:21891
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=data-prepper:21892
      - OTEL_SERVICE_NAME=demo-service
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=poc,deployment.environment=dev
    ports:
      - "8080:8080"
    networks:
      - opensearch-net
    depends_on:
      - data-prepper

volumes:
  opensearch-data:


networks:
  opensearch-net:
    driver: bridge
